name: Build release

on:
  push:
    tags:
      - "v*"

jobs:
  source-release:
    name: Make source release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Python dependencies
        run: pip install tox build
      - name: Build
        run: make dist
      - name: Make the release
        run: gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name}}" dist/*
